services:
  supplier.ingestion.orchestrator.api:
    image: ${DOCKER_REGISTRY-}supplieringestionorchestratorapi
    build:
      context: ..
      dockerfile: src/Supplier.Ingestion.Orchestrator.Api/Dockerfile
    environment:
      - ConnectionStrings__Kafka=kafka:29092
      - ConnectionStrings__MongoDb=mongodb://${MONGO_APP_USERNAME}:${MONGO_APP_PASSWORD}@mongo:27017/IngestionRefineryDb
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - Anthropic__ApiKey=${ANTHROPIC_API_KEY}
      - Kafka__SigningKey=${KAFKA_SIGNING_KEY}
    ports:
      - "8080:8080"
      - "8081:8081"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/health/ready || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      kafka:
        condition: service_healthy
      mongo:
        condition: service_healthy
      otel-collector:
        condition: service_started
    networks:
      - saga-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka
    container_name: kafka
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qg
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: kafka-broker-api-versions --bootstrap-server localhost:9092
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - saga-net

  mongo:
    image: mongo:8.0
    container_name: saga-mongo
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_APP_USERNAME: ${MONGO_APP_USERNAME}
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - ./files/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')" --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - saga-net

  mongo-express:
    image: mongo-express:1.0.2
    container_name: saga-mongo-ui
    restart: always
    ports:
      - "127.0.0.1:8181:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - saga-net

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "127.0.0.1:8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: Local-Cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - saga-net

  init-kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - saga-net
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      echo -e 'Aguardando Kafka...'
      cub kafka-ready -b kafka:29092 1 20
      kafka-topics --create --if-not-exists --bootstrap-server kafka:29092 --partitions 2 --replication-factor 1 --topic source.supplier-a.v1
      kafka-topics --create --if-not-exists --bootstrap-server kafka:29092 --partitions 2 --replication-factor 1 --topic source.supplier-b.v1
      kafka-topics --create --if-not-exists --bootstrap-server kafka:29092 --partitions 2 --replication-factor 1 --topic target.processed.data.v1
      kafka-topics --create --if-not-exists --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 --topic target.invalid.data.v1 --config retention.ms=2592000000
      echo -e 'Tópicos criados!'
      "

  supplier.a.producer.api:
    image: ${DOCKER_REGISTRY-}supplieraproducerapi
    build:
      context: ..
      dockerfile: src/Supplier.A.Producer.Api/Dockerfile
    environment:
      - ConnectionStrings__Kafka=kafka:29092
      - Kafka__SigningKey=${KAFKA_SIGNING_KEY}
    ports:
      - "8082:8080"
    depends_on:
      kafka:
        condition: service_healthy
      init-kafka:
        condition: service_completed_successfully
    networks:
      - saga-net

  supplier.b.producer.api:
    image: ${DOCKER_REGISTRY-}supplierbproducerapi
    build:
      context: ..
      dockerfile: src/Supplier.B.Producer.Api/Dockerfile
    environment:
      - ConnectionStrings__Kafka=kafka:29092
      - Kafka__SigningKey=${KAFKA_SIGNING_KEY}
    ports:
      - "8083:8080"
    depends_on:
      kafka:
        condition: service_healthy
      init-kafka:
        condition: service_completed_successfully
    networks:
      - saga-net

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--web.enable-remote-write-receiver"
      - "--enable-feature=exemplar-storage"
    volumes:
      - ./files/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./files/alert.rules.yaml:/etc/prometheus/alert.rules.yaml
    ports:
      - "127.0.0.1:9090:9090"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - saga-net

  loki:
    image: grafana/loki:3.4.2
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - ./files/loki.yaml:/etc/loki/local-config.yaml
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - saga-net

  tempo:
    image: grafana/tempo:2.7.2
    container_name: tempo
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    volumes:
      - ./files/tempo.yaml:/etc/tempo/tempo.yaml
      - tempo-data:/var/tempo
    ports:
      - "127.0.0.1:3200:3200"
    depends_on:
      prometheus:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3200/ready || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - saga-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.123.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./files/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "127.0.0.1:4317:4317"
      - "127.0.0.1:4318:4318"
    depends_on:
      loki:
        condition: service_healthy
      tempo:
        condition: service_healthy
    networks:
      - saga-net

  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=false
    depends_on:
      loki:
        condition: service_healthy
      prometheus:
        condition: service_healthy
      tempo:
        condition: service_healthy
    volumes:
      - ./files/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./files/grafana/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - saga-net

volumes:
  mongo-data:
  kafka-data:
  tempo-data:

networks:
  saga-net:
    driver: bridge
